services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_security_auth__minimum__password__length=4
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  backend:
    build: .
    image: woojeongalexcloud-backend
    container_name: backend
    network_mode: host
    env_file:
      - .env
    depends_on:
      - pgvector
      - neo4j
    restart: unless-stopped


volumes:
  pgvector_data:
  neo4j_data:
